### ISSUE TITLE
Not able to connect to starknet-mainnet

### ISSUE THREAD

**Issue by dimandi-deqode** [starknet-graph/quickstart#1]
@xJonathanLEI, I am facing an issue in running the starknet graph node. I mentioned my starknet-mainnet infura url in the config.toml file and executed the docker. The below is the kind of logs I am getting. Please help me how can I resolve the issue and thereby index the starknet data using a subgraph

quickstart-graph-node-1  | Jun 18 13:40:19.671 INFO Graph Node version: 0.29.0 (2023-02-18)
quickstart-graph-node-1  | Jun 18 13:40:19.671 WARN GRAPH_POI_ACCESS_TOKEN not set; might leak POIs to the public via GraphQL
quickstart-graph-node-1  | Jun 18 13:40:19.672 INFO Reading configuration file `/config.toml`
quickstart-graph-node-1  | Jun 18 13:40:19.672 WARN No fork base URL specified, subgraph forking is disabled
quickstart-graph-node-1  | Jun 18 13:40:19.672 INFO Starting up
quickstart-graph-node-1  | Jun 18 13:40:19.672 INFO Trying IPFS node at: http://ipfs:5001/
quickstart-graph-node-1  | Jun 18 13:40:19.676 INFO Configuring firehose endpoint, provider: starknet-mainnet-0
quickstart-graph-node-1  | Jun 18 13:40:19.677 INFO Successfully connected to IPFS node at: http://ipfs:5001/
quickstart-graph-node-1  | Jun 18 13:40:19.681 WARN Expensive queries file not set to a valid file: /etc/graph-node/expensive-queries.txt
quickstart-graph-node-1  | Jun 18 13:40:19.690 INFO Connecting to Postgres, weight: 1, conn_pool_size: 10, url: postgresql://graph-node:HIDDEN_PASSWORD@postgres:5432/graph-node, pool: main, shard: primary
quickstart-graph-node-1  | Jun 18 13:40:19.690 INFO Pool successfully connected to Postgres, pool: main, shard: primary, component: Store
quickstart-graph-node-1  | Jun 18 13:40:19.694 INFO Setting up fdw, pool: main, shard: primary, component: ConnectionPool
quickstart-graph-node-1  | Jun 18 13:40:19.702 INFO Running migrations, pool: main, shard: primary, component: ConnectionPool
quickstart-graph-node-1  | Jun 18 13:40:20.422 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
quickstart-graph-node-1  | Jun 18 13:40:20.423 INFO Mapping primary, pool: main, shard: primary, component: ConnectionPool
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-0, provider: starknet-mainnet-0-0
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-0
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-1, provider: starknet-mainnet-0-1
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-1
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-2, provider: starknet-mainnet-0-2
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-2
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-3, provider: starknet-mainnet-0-3
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-3
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-4, provider: starknet-mainnet-0-4
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-4
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-5, provider: starknet-mainnet-0-5
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-5
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-6, provider: starknet-mainnet-0-6
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-6
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-7, provider: starknet-mainnet-0-7
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-7
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-8, provider: starknet-mainnet-0-8
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-8
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-9, provider: starknet-mainnet-0-9
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-9
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-10, provider: starknet-mainnet-0-10
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-10
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-11, provider: starknet-mainnet-0-11
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-11
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-12, provider: starknet-mainnet-0-12
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-12
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-13, provider: starknet-mainnet-0-13
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-13
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-14, provider: starknet-mainnet-0-14
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-14
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-15, provider: starknet-mainnet-0-15
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-15
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-16, provider: starknet-mainnet-0-16
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-16
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-17, provider: starknet-mainnet-0-17
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-17
quickstart-graph-node-1  | Jun 18 13:40:20.434 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-18, provider: starknet-mainnet-0-18
quickstart-graph-node-1  | Jun 18 13:40:20.435 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-18
quickstart-graph-node-1  | Jun 18 13:40:20.435 INFO Connecting to Firehose to get chain identifier, provider: starknet-mainnet-0-19, provider: starknet-mainnet-0-19
quickstart-graph-node-1  | Jun 18 13:40:20.435 INFO Requesting genesis block from firehose, provider: starknet-mainnet-0-19
quickstart-graph-node-1  | Jun 18 13:40:21.477 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-14
quickstart-graph-node-1  | Jun 18 13:40:21.477 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-9
quickstart-graph-node-1  | Jun 18 13:40:21.485 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-16
quickstart-graph-node-1  | Jun 18 13:40:21.495 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-2
quickstart-graph-node-1  | Jun 18 13:40:21.507 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-10
quickstart-graph-node-1  | Jun 18 13:40:21.514 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-17
quickstart-graph-node-1  | Jun 18 13:40:21.550 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-15
quickstart-graph-node-1  | Jun 18 13:40:21.555 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-18
quickstart-graph-node-1  | Jun 18 13:40:21.555 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-3
quickstart-graph-node-1  | Jun 18 13:40:21.555 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-12
quickstart-graph-node-1  | Jun 18 13:40:21.560 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-5
quickstart-graph-node-1  | Jun 18 13:40:21.566 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-8
quickstart-graph-node-1  | Jun 18 13:40:21.576 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-1
quickstart-graph-node-1  | Jun 18 13:40:21.590 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-13
quickstart-graph-node-1  | Jun 18 13:40:21.597 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-7
quickstart-graph-node-1  | Jun 18 13:40:21.597 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-4
quickstart-graph-node-1  | Jun 18 13:40:21.597 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-6
quickstart-graph-node-1  | Jun 18 13:40:21.617 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-0
quickstart-graph-node-1  | Jun 18 13:40:21.659 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-19
quickstart-graph-node-1  | Jun 18 13:40:21.764 ERRO Connection to provider failed. Not using this provider, error: firehose error status: Unknown, message: "grpc-status header missing, mapped from HTTP status code 464", details: [], metadata: MetadataMap { headers: {} }, provider: starknet-mainnet-0-11
quickstart-graph-node-1  | Jun 18 13:40:21.764 ERRO No non-broken providers available for chain starknet-mainnet; ignoring this chain
quickstart-graph-node-1  | Jun 18 13:40:21.940 INFO Creating LoadManager in disabled mode, component: LoadManager
quickstart-graph-node-1  | Jun 18 13:40:21.940 INFO Starting firehose block ingestors with 0 chains []
quickstart-graph-node-1  | Jun 18 13:40:21.940 INFO Starting firehose block ingestors with 0 chains []
quickstart-graph-node-1  | Jun 18 13:40:21.940 INFO Starting firehose block ingestors with 0 chains []
quickstart-graph-node-1  | Jun 18 13:40:21.940 INFO Starting firehose block ingestors with 0 chains []
quickstart-graph-node-1  | Jun 18 13:40:21.940 INFO Starting job runner with 4 jobs, component: JobRunner
quickstart-graph-node-1  | Jun 18 13:40:21.942 INFO Starting JSON-RPC admin server at: http://localhost:8020, component: JsonRpcServer
quickstart-graph-node-1  | Jun 18 13:40:21.942 INFO Starting GraphQL HTTP server at: http://localhost:8000, component: GraphQLServer
quickstart-graph-node-1  | Jun 18 13:40:21.942 INFO Starting index node server at: http://localhost:8030, component: IndexNodeServer
quickstart-graph-node-1  | Jun 18 13:40:21.942 INFO Started all assigned subgraphs, node_id: default, count: 0, component: SubgraphRegistrar
quickstart-graph-node-1  | Jun 18 13:40:21.942 INFO Starting metrics server at: http://localhost:8040, component: MetricsServer
quickstart-graph-node-1  | Jun 18 13:40:21.942 INFO Starting GraphQL WebSocket server at: ws://localhost:8001, component: SubscriptionServer

**Comment by dimandi-deqode** [comment]
Please show some solution.

**Comment by xJonathanLEI** [comment]
As mentioned in the instructions, you're supposed to add your RPC URL to the `.env`, not `config.toml`. `config.toml` is for configuring `graph-node`, which expects a gRPC endpoint, not a JSON-RPC endpoint.
