### ISSUE TITLE
The graph not working with public rpc endpoints

### ISSUE THREAD

**Issue by blockchainluffy** [starknet-graph/quickstart#2]
Hi, I am not able to run starknet-graph using the docker compose in https://github.com/starknet-graph/quickstart guide. For ETHEREUM-RPC environment variable, I am using public rpc providors. I have tried with alchemy, chainbase, infura, blast-api.

`The firehose-reader stops with the following error, eventually causing graph-node also to stop.
quickstart-firehose-reader-1   | {"severity":"INFO","timestamp":"2023-09-22T06:58:04.966849635Z","logger":"firestark","message":"waiting for all apps termination...","logging.googleapis.com/labels":{}}
quickstart-firehose-reader-1   | {"severity":"INFO","timestamp":"2023-09-22T06:58:04.966889532Z","logger":"firestark","message":"all apps terminated gracefully","logging.googleapis.com/labels":{}}
quickstart-firehose-reader-1   | Error: unable to launch: instance "dummy-blockchain" stopped (exit code: 1), shutting down
quickstart-firehose-reader-1   | {"severity":"ERROR","timestamp":"2023-09-22T06:58:04.966960491Z","logger":"firestark","message":"failed to run","error":"unable to launch: instance \"dummy-blockchain\" stopped (exit code: 1), shutting down","logging.googleapis.com/labels":{},"serviceContext":{"service":"unknown"}}`

**Comment by xJonathanLEI** [comment]
It's `ETHEREUM_RPC` not `ETHEREUM-RPC`.
